[package]
name = "rust_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
quick-xml = "0.30"
scraper = "0.18"
regex = "1.9"




